/**
 * Smart Manager APILib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { ApiError } from '../core';

/**
 * Creates an instance of DaliScan400
 */
interface DaliScan400 {
  daliScanErrorMessage?: string;
}

export class DaliScan400Error extends ApiError<DaliScan400> {}
