/**
 * Smart Manager APILib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { ApiError } from '../core';

/**
 * Creates an instance of DaliScan503
 */
interface DaliScan503 {
  daliScanErrorMessage?: string;
}

export class DaliScan503Error extends ApiError<DaliScan503> {}
