/**
 * Smart Manager APILib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { ApiError } from '../core';

/**
 * Creates an instance of Peripherals404
 */
interface Peripherals404 {
  message: string;
}

export class Peripherals404Error extends ApiError<Peripherals404> {}
