/**
 * Smart Manager APILib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { ApiError } from '../core';
import { Details } from '../models/details';

/**
 * Creates an instance of ValidateErrorJSON
 */
interface ValidateErrorJSON {
  message: string;
  details: Record<string, Details>;
}

export class ValidateErrorJSONError extends ApiError<ValidateErrorJSON> {}
