/**
 * Smart Manager APILib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { ApiResponse, RequestOptions } from '../core';
import { BaseController } from './baseController';

export class HealthController extends BaseController {
  /**
   * Healthcheck endpoint
   *
   * @return Response from the API call
   */
  async ping(
    requestOptions?: RequestOptions
  ): Promise<ApiResponse<void>> {
    const req = this.createRequest('GET', '/ping');
    req.authenticate(false);
    return req.call(requestOptions);
  }
}
