/**
 * Smart Manager APILib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { ApiResponse, RequestOptions } from '../core';
import {
  SmartManagerIssue,
  smartManagerIssueSchema,
} from '../models/smartManagerIssue';
import { array } from '../schema';
import { BaseController } from './baseController';

export class IssuesController extends BaseController {
  /**
   * Get issues
   *
   * @return Response from the API call
   */
  async getIssues(
    requestOptions?: RequestOptions
  ): Promise<ApiResponse<SmartManagerIssue[]>> {
    const req = this.createRequest('GET', '/issues');
    req.authenticate(false);
    return req.callAsJson(array(smartManagerIssueSchema), requestOptions);
  }
}
