/**
 * Smart Manager APILib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { ApiResponse, RequestOptions } from '../core';
import { BaseController } from './baseController';

export class StopController extends BaseController {
  /**
   * Stop the webserver and the access point
   *
   * @return Response from the API call
   */
  async stop(
    requestOptions?: RequestOptions
  ): Promise<ApiResponse<void>> {
    const req = this.createRequest('POST', '/stop');
    req.authenticate(false);
    return req.call(requestOptions);
  }
}
