/**
 * Smart Manager APILib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { boolean, number, object, Schema, string } from '../schema';
import {
  WifiFrequencyTypeEnum,
  wifiFrequencyTypeEnumSchema,
} from './wifiFrequencyTypeEnum';

export interface AccessPoint {
  /** Name of the access point */
  ssid: string;
  /** Unique identifier of this access point */
  bssid: string;
  /** What frequency channel this access point is operating on */
  channel: number;
  frequency: WifiFrequencyTypeEnum;
  /** Whether user has to provide a passphrase when connecting to this wifi */
  isPublic: boolean;
  /** The current signal quality of the access point, in percent */
  signalStrength: number;
  /**
   * Whether the network is known. i.e. we've previously connected to it and
   * have it's connection settings stored on smart-manager.
   */
  isKnown: boolean;
}

export const accessPointSchema: Schema<AccessPoint> = object({
  ssid: ['ssid', string()],
  bssid: ['bssid', string()],
  channel: ['channel', number()],
  frequency: ['frequency', wifiFrequencyTypeEnumSchema],
  isPublic: ['isPublic', boolean()],
  signalStrength: ['signalStrength', number()],
  isKnown: ['isKnown', boolean()],
});
