/**
 * Smart Manager APILib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { Schema, stringEnum } from '../schema';

/**
 * Enum for ActiveConnectionStateEnum
 */
export enum ActiveConnectionStateEnum {
  UNKNOWN = 'UNKNOWN',
  ACTIVATING = 'ACTIVATING',
  ACTIVATED = 'ACTIVATED',
  DEACTIVATING = 'DEACTIVATING',
  DEACTIVATED = 'DEACTIVATED',
}

/**
 * Schema for ActiveConnectionStateEnum
 */
export const activeConnectionStateEnumSchema: Schema<ActiveConnectionStateEnum> = stringEnum(ActiveConnectionStateEnum);
