/**
 * Smart Manager APILib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { array, object, Schema, string } from '../schema';
import {
  AirSmartSensorModuleEnum,
  airSmartSensorModuleEnumSchema,
} from './airSmartSensorModuleEnum';
import {
  DeviceCategoryEnum,
  deviceCategoryEnumSchema,
} from './deviceCategoryEnum';
import {
  PeripheralClassesEnum,
  peripheralClassesEnumSchema,
} from './peripheralClassesEnum';

export interface AirSmartTemplate {
  /** Unique (within template) device identifier */
  id: string;
  /** Human-friendly label for the device */
  label: string;
  /** Refers to the class within the code that represents a device */
  className: PeripheralClassesEnum;
  /**
   * We categorise devices mainly to automate commissioning of "wired"
   * and "multisenseNetwork"s (e.g. create those peripherals
   * without engineers having to manually link them on the native app)
   */
  deviceCategory: DeviceCategoryEnum;
  /** Additional modules that can be connected to the Air Smart */
  modules: AirSmartSensorModuleEnum[];
}

export const airSmartTemplateSchema: Schema<AirSmartTemplate> = object({
  id: ['id', string()],
  label: ['label', string()],
  className: ['className', peripheralClassesEnumSchema],
  deviceCategory: ['deviceCategory', deviceCategoryEnumSchema],
  modules: ['modules', array(airSmartSensorModuleEnumSchema)],
});
