/**
 * Smart Manager APILib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { Schema, stringEnum } from '../schema';

/**
 * Enum for AirSmartSensorModuleEnum
 */
export enum AirSmartSensorModuleEnum {
  TempHumidity = 'tempHumidity',
  Voc = 'voc',
  Gas = 'gas',
  Pm = 'pm',
  Oxygen = 'oxygen',
  Co2 = 'co2',
}

/**
 * Schema for AirSmartSensorModuleEnum
 */
export const airSmartSensorModuleEnumSchema: Schema<AirSmartSensorModuleEnum> = stringEnum(AirSmartSensorModuleEnum);
