/**
 * Smart Manager APILib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { Schema, stringEnum } from '../schema';

/**
 * Enum for BalenaServiceStatusEnum
 */
export enum BalenaServiceStatusEnum {
  Stopping = 'Stopping',
  Stopped = 'Stopped',
  Running = 'Running',
  Installing = 'Installing',
  Installed = 'Installed',
  Dead = 'Dead',
  Paused = 'paused',
  Restarting = 'restarting',
  Removing = 'removing',
  Exited = 'exited',
}

/**
 * Schema for BalenaServiceStatusEnum
 */
export const balenaServiceStatusEnumSchema: Schema<BalenaServiceStatusEnum> = stringEnum(BalenaServiceStatusEnum);
