/**
 * Smart Manager APILib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { Schema, stringEnum } from '../schema';

/**
 * Enum for BalenaSupervisorStatusEnum
 */
export enum BalenaSupervisorStatusEnum {
  Healthy = 'healthy',
  Unhealthy = 'unhealthy',
  Mocked = 'mocked',
}

/**
 * Schema for BalenaSupervisorStatusEnum
 */
export const balenaSupervisorStatusEnumSchema: Schema<BalenaSupervisorStatusEnum> = stringEnum(BalenaSupervisorStatusEnum);
