/**
 * Smart Manager APILib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { object, Schema, string } from '../schema';
import {
  DeviceCategory1Enum,
  deviceCategory1EnumSchema,
} from './deviceCategory1Enum';
import {
  PeripheralClasses1Enum,
  peripheralClasses1EnumSchema,
} from './peripheralClasses1Enum';

export interface BaseDevice {
  /** Unique (within template) device identifier */
  id: string;
  /** Human-friendly label for the device */
  label: string;
  /** Refers to the class within the code that represents this device */
  className: PeripheralClasses1Enum;
  /** Device category */
  deviceCategory: DeviceCategory1Enum;
}

export const baseDeviceSchema: Schema<BaseDevice> = object({
  id: ['id', string()],
  label: ['label', string()],
  className: ['className', peripheralClasses1EnumSchema],
  deviceCategory: ['deviceCategory', deviceCategory1EnumSchema],
});
