/**
 * Smart Manager APILib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { object, Schema } from '../schema';
import { ActionEnum, actionEnumSchema } from './actionEnum';

export interface CaptureLogsBody {
  action: ActionEnum;
}

export const captureLogsBodySchema: Schema<CaptureLogsBody> = object({
  action: ['action', actionEnumSchema],
});
