/**
 * Smart Manager APILib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { boolean, object, Schema } from '../schema';

export interface CaptureLogsStatus {
  isStreamingLogs: boolean;
}

export const captureLogsStatusSchema: Schema<CaptureLogsStatus> = object({
  isStreamingLogs: ['isStreamingLogs', boolean()],
});
