/**
 * Smart Manager APILib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { array, lazy, object, optional, Schema, string } from '../schema';
import { Device1, device1Schema } from './device1';

export interface ConfigTemplatesCreateResponse {
  templateId?: string;
  templateLabel?: string;
  devices?: Device1[];
}

export const configTemplatesCreateResponseSchema: Schema<ConfigTemplatesCreateResponse> = object(
  {
    templateId: ['templateId', optional(string())],
    templateLabel: ['templateLabel', optional(string())],
    devices: ['devices', optional(array(lazy(() => device1Schema)))],
  }
);
