/**
 * Smart Manager APILib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { boolean, object, optional, Schema } from '../schema';
import {
  HotspotAction1Enum,
  hotspotAction1EnumSchema,
} from './hotspotAction1Enum';

export interface CreateWifiConnectionResponse {
  /** What will be done to hotspot if we were to connect to this wifi network */
  hotspotAction?: HotspotAction1Enum;
  /** What the request made with dryRun flag or not */
  dryRun?: boolean;
}

export const createWifiConnectionResponseSchema: Schema<CreateWifiConnectionResponse> = object(
  {
    hotspotAction: ['hotspotAction', optional(hotspotAction1EnumSchema)],
    dryRun: ['dryRun', optional(boolean())],
  }
);
