/**
 * Smart Manager APILib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { array, lazy, object, Schema, string } from '../schema';
import { CreatePeripheral, createPeripheralSchema } from './createPeripheral';

/** Create template body */
export interface CreateTemplate {
  templateLabel: string;
  devices: CreatePeripheral[];
}

export const createTemplateSchema: Schema<CreateTemplate> = object({
  templateLabel: ['templateLabel', string()],
  devices: ['devices', array(lazy(() => createPeripheralSchema))],
});
