/**
 * Smart Manager APILib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { boolean, object, optional, Schema } from '../schema';
import {
  HotspotActionEnum,
  hotspotActionEnumSchema,
} from './hotspotActionEnum';

export interface CreateWifiConnectionResponse {
  hotspotAction?: HotspotActionEnum;
  /** What the request made with dryRun flag or not */
  dryRun?: boolean;
}

export const createWifiConnectionResponseSchema: Schema<CreateWifiConnectionResponse> = object(
  {
    hotspotAction: ['hotspotAction', optional(hotspotActionEnumSchema)],
    dryRun: ['dryRun', optional(boolean())],
  }
);
