/**
 * Smart Manager APILib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { boolean, object, optional, Schema, string } from '../schema';

export interface CreateWifiConnection {
  /** Identifier of the network we want to connect to */
  ssid: string;
  /** Applicable only if access point is not public */
  passphrase?: string;
  /** If true, it does everything needed to create a wifi connection, except actually creating the wifi connection */
  dryRun: boolean;
}

export const createWifiConnectionSchema: Schema<CreateWifiConnection> = object({
  ssid: ['ssid', string()],
  passphrase: ['passphrase', optional(string())],
  dryRun: ['dryRun', boolean()],
});
