/**
 * Smart Manager APILib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { object, Schema, string } from '../schema';

export interface DeleteWifiConnection {
  ssid: string;
}

export const deleteWifiConnectionSchema: Schema<DeleteWifiConnection> = object({
  ssid: ['ssid', string()],
});
