/**
 * Smart Manager APILib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { object, Schema, string, unknown } from '../schema';

export interface Details {
  value?: unknown;
  message: string;
}

export const detailsSchema: Schema<Details> = object({
  value: ['value', unknown()],
  message: ['message', string()],
});
