/**
 * Smart Manager APILib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import {
  array,
  nullable,
  object,
  optional,
  Schema,
  string,
  unknown,
} from '../schema';
import {
  PeripheralClasses3Enum,
  peripheralClasses3EnumSchema,
} from './peripheralClasses3Enum';

export interface Device1 {
  /** The name of the class that handles this peripheral e.g. enocean_dimmer */
  className?: PeripheralClasses3Enum;
  /** The id of the end device e.g. aabbccdd as an enocean id for an enocean switch or 123 as a multisense network id for a smart power meter */
  hardwareId?: string;
  modules?: unknown[] | null;
  /** The id of the multisense that this peripheral is linked to. */
  gatewayId?: string;
}

export const device1Schema: Schema<Device1> = object({
  className: ['className', optional(peripheralClasses3EnumSchema)],
  hardwareId: ['hardwareId', optional(string())],
  modules: ['modules', optional(nullable(array(unknown())))],
  gatewayId: ['gatewayId', optional(string())],
});
