/**
 * Smart Manager APILib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import {
  array,
  nullable,
  object,
  optional,
  Schema,
  string,
  unknown,
} from '../schema';
import {
  PeripheralClassesEnum,
  peripheralClassesEnumSchema,
} from './peripheralClassesEnum';

export interface Device1 {
  /** Refers to the class within the code that represents a device */
  className?: PeripheralClassesEnum;
  /** The id of the end device e.g. aabbccdd as an enocean id for an enocean switch or 123 as a multisense network id for a smart power meter */
  hardwareId?: string;
  modules?: unknown[] | null;
  /** The id of the multisense that this peripheral is linked to. */
  gatewayId?: string;
}

export const device1Schema: Schema<Device1> = object({
  className: ['className', optional(peripheralClassesEnumSchema)],
  hardwareId: ['hardwareId', optional(string())],
  modules: ['modules', optional(nullable(array(unknown())))],
  gatewayId: ['gatewayId', optional(string())],
});
