/**
 * Smart Manager APILib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { Schema, stringEnum } from '../schema';

/**
 * Enum for DeviceCategoryEnum
 */
export enum DeviceCategoryEnum {
  Relay = 'relay',
  Input = 'input',
  Wireless = 'wireless',
  MultisenseNetwork = 'multisenseNetwork',
}

/**
 * Schema for DeviceCategoryEnum
 */
export const deviceCategoryEnumSchema: Schema<DeviceCategoryEnum> = stringEnum(DeviceCategoryEnum);
