/**
 * Smart Manager APILib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { Schema, stringEnum } from '../schema';

/**
 * Enum for DeviceTypeEnum
 */
export enum DeviceTypeEnum {
  UNKNOWN = 'UNKNOWN',
  MULTISENSE = 'MULTISENSE',
  POWERMETER = 'POWER_METER',
  AIRQUALITYSENSOR = 'AIR_QUALITY_SENSOR',
}

/**
 * Schema for DeviceTypeEnum
 */
export const deviceTypeEnumSchema: Schema<DeviceTypeEnum> = stringEnum(DeviceTypeEnum);
