/**
 * Smart Manager APILib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { Schema, stringEnum } from '../schema';

/**
 * Enum for EnoceanDimmableLightInstructionsEnum
 */
export enum EnoceanDimmableLightInstructionsEnum {
  TeachIn = 'teachIn',
  On = 'on',
  Off = 'off',
  FullBrightness = 'fullBrightness',
  PressUp = 'pressUp',
  PressDown = 'pressDown',
  Release = 'release',
}

/**
 * Schema for EnoceanDimmableLightInstructionsEnum
 */
export const enoceanDimmableLightInstructionsEnumSchema: Schema<EnoceanDimmableLightInstructionsEnum> = stringEnum(EnoceanDimmableLightInstructionsEnum);
