/**
 * Smart Manager APILib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import {
  boolean,
  lazy,
  nullable,
  number,
  object,
  optional,
  Schema,
  string,
} from '../schema';
import { DeviceTypeEnum, deviceTypeEnumSchema } from './deviceTypeEnum';
import {
  HighlightTypeEnum,
  highlightTypeEnumSchema,
} from './highlightTypeEnum';
import { IotIColour, iotIColourSchema } from './iotIColour';

export interface HighlightCommand {
  /** Set to true to turn the LED off */
  off: boolean | null;
  /** Properties of a Colour. RGB Format */
  colour?: IotIColour;
  /** Turn LED on for `duration` in seconds, after which LED light is turned off. */
  duration?: number | null;
  id?: string;
  deviceType?: DeviceTypeEnum;
  highlightType?: HighlightTypeEnum;
}

export const highlightCommandSchema: Schema<HighlightCommand> = object({
  off: ['off', nullable(boolean())],
  colour: ['colour', optional(lazy(() => iotIColourSchema))],
  duration: ['duration', optional(nullable(number()))],
  id: ['id', optional(string())],
  deviceType: ['deviceType', optional(deviceTypeEnumSchema)],
  highlightType: ['highlightType', optional(highlightTypeEnumSchema)],
});
