/**
 * Smart Manager APILib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { Schema, stringEnum } from '../schema';

/**
 * Enum for HotspotActionEnum
 */
export enum HotspotActionEnum {
  Stop = 'stop',
  Reconfigure = 'reconfigure',
}

/**
 * Schema for HotspotActionEnum
 */
export const hotspotActionEnumSchema: Schema<HotspotActionEnum> = stringEnum(HotspotActionEnum);
