/**
 * Smart Manager APILib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { Schema, stringEnum } from '../schema';

/**
 * Enum for HotspotAction1Enum
 */
export enum HotspotAction1Enum {
  Stop = 'stop',
  Reconfigure = 'reconfigure',
}

/**
 * Schema for HotspotAction1Enum
 */
export const hotspotAction1EnumSchema: Schema<HotspotAction1Enum> = stringEnum(HotspotAction1Enum);
