/**
 * Smart Manager APILib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { nullable, number, object, Schema } from '../schema';

/** Properties of a Colour. RGB Format */
export interface IotIColour {
  /** Colour red */
  red: number | null;
  /** Colour blue */
  blue: number | null;
  /** Colour green */
  green: number | null;
}

export const iotIColourSchema: Schema<IotIColour> = object({
  red: ['red', nullable(number())],
  blue: ['blue', nullable(number())],
  green: ['green', nullable(number())],
});
