/**
 * Smart Manager APILib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { object, Schema, string } from '../schema';

export interface MqttStatusChange {
  status: string;
}

export const mqttStatusChangeSchema: Schema<MqttStatusChange> = object({
  status: ['status', string()],
});
