/**
 * Smart Manager APILib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { Schema, stringEnum } from '../schema';

/**
 * Enum for MultisenseModuleEnum
 */
export enum MultisenseModuleEnum {
  Ble = 'ble',
  Enocean = 'enocean',
  Zigbee = 'zigbee',
  UibTemperature = 'uibTemperature',
}

/**
 * Schema for MultisenseModuleEnum
 */
export const multisenseModuleEnumSchema: Schema<MultisenseModuleEnum> = stringEnum(MultisenseModuleEnum);
