/**
 * Smart Manager APILib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { Schema, stringEnum } from '../schema';

/**
 * Enum for MultisenseModuleGenericEnum
 */
export enum MultisenseModuleGenericEnum {
  Ble = 'ble',
  Enocean = 'enocean',
  Zigbee = 'zigbee',
  Universalinput = 'universalinput',
  Dali = 'dali',
}

/**
 * Schema for MultisenseModuleGenericEnum
 */
export const multisenseModuleGenericEnumSchema: Schema<MultisenseModuleGenericEnum> = stringEnum(MultisenseModuleGenericEnum);
