/**
 * Smart Manager APILib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { lazy, object, Schema } from '../schema';
import { Hotspot, hotspotSchema } from './hotspot';
import { Wifi, wifiSchema } from './wifi';

/** If supervisor is not healthy, some network info will be undefined and unobtainable */
export interface NetworkInfo {
  hotspot: Hotspot;
  wifi: Wifi;
}

export const networkInfoSchema: Schema<NetworkInfo> = object({
  hotspot: ['hotspot', lazy(() => hotspotSchema)],
  wifi: ['wifi', lazy(() => wifiSchema)],
});
