/**
 * Smart Manager APILib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { number, object, Schema, string } from '../schema';

export interface OpenZigbeeNetworkOptions {
  /** Multisense ID */
  id: string;
  /** Amount of time in ms before closing the zigbee network again */
  timeout: number;
}

export const openZigbeeNetworkOptionsSchema: Schema<OpenZigbeeNetworkOptions> = object(
  { id: ['id', string()], timeout: ['timeout', number()] }
);
