/**
 * Smart Manager APILib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { Schema, stringEnum } from '../schema';

/**
 * Enum for PeripheralClasses1Enum
 */
export enum PeripheralClasses1Enum {
  DigitalInputDoorContact = 'DigitalInputDoorContact',
  ExtractorFan = 'ExtractorFan',
  IlluminatedMirror = 'IlluminatedMirror',
  Lock = 'Lock',
  PanelHeater = 'PanelHeater',
  RelayCanopyFan = 'RelayCanopyFan',
  RelayHob = 'RelayHob',
  RelayLight = 'RelayLight',
  TowelRail = 'TowelRail',
  EnoceanWindowContact = 'EnoceanWindowContact',
  EnoceanRockerSwitch = 'EnoceanRockerSwitch',
  EnoceanLeakDetector = 'EnoceanLeakDetector',
  EnoceanTemperatureSensor = 'EnoceanTemperatureSensor',
  EnoceanDimmableLight = 'EnoceanDimmableLight',
  EnoceanHeatDetector = 'EnoceanHeatDetector',
  ZigbeeBlind = 'ZigbeeBlind',
  AirSmart = 'AirSmart',
  Multisense = 'Multisense',
  PowerMeter = 'PowerMeter',
  DaliLight = 'DaliLight',
}

/**
 * Schema for PeripheralClasses1Enum
 */
export const peripheralClasses1EnumSchema: Schema<PeripheralClasses1Enum> = stringEnum(PeripheralClasses1Enum);
