/**
 * Smart Manager APILib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { object, Schema, unknown } from '../schema';

export interface PeripheralsPointsRequest {
  value?: unknown;
}

export const peripheralsPointsRequestSchema: Schema<PeripheralsPointsRequest> = object(
  { value: ['value', unknown()] }
);
