/**
 * Smart Manager APILib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { Schema, stringEnum } from '../schema';

/**
 * Enum for PeripheralClasses3Enum
 */
export enum PeripheralClasses3Enum {
  DigitalInputDoorContact = 'DigitalInputDoorContact',
  ExtractorFan = 'ExtractorFan',
  IlluminatedMirror = 'IlluminatedMirror',
  Lock = 'Lock',
  PanelHeater = 'PanelHeater',
  RelayCanopyFan = 'RelayCanopyFan',
  RelayHob = 'RelayHob',
  RelayLight = 'RelayLight',
  TowelRail = 'TowelRail',
  EnoceanWindowContact = 'EnoceanWindowContact',
  EnoceanRockerSwitch = 'EnoceanRockerSwitch',
  EnoceanLeakDetector = 'EnoceanLeakDetector',
  EnoceanTemperatureSensor = 'EnoceanTemperatureSensor',
  EnoceanDimmableLight = 'EnoceanDimmableLight',
  EnoceanHeatDetector = 'EnoceanHeatDetector',
  ZigbeeBlind = 'ZigbeeBlind',
  AirSmart = 'AirSmart',
  Multisense = 'Multisense',
  PowerMeter = 'PowerMeter',
  DaliLight = 'DaliLight',
}

/**
 * Schema for PeripheralClasses3Enum
 */
export const peripheralClasses3EnumSchema: Schema<PeripheralClasses3Enum> = stringEnum(PeripheralClasses3Enum);
