/**
 * Smart Manager APILib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { object, Schema, string } from '../schema';
import {
  DeviceCategoryEnum,
  deviceCategoryEnumSchema,
} from './deviceCategoryEnum';
import {
  PeripheralClassesEnum,
  peripheralClassesEnumSchema,
} from './peripheralClassesEnum';

export interface PowerMeterTemplate {
  /** Unique (within template) device identifier */
  id: string;
  /** Human-friendly label for the device */
  label: string;
  /** Refers to the class within the code that represents a device */
  className: PeripheralClassesEnum;
  /**
   * We categorise devices mainly to automate commissioning of "wired"
   * and "multisenseNetwork"s (e.g. create those peripherals
   * without engineers having to manually link them on the native app)
   */
  deviceCategory: DeviceCategoryEnum;
  /** Valid values are 1|2|3 */
  channelId: string;
}

export const powerMeterTemplateSchema: Schema<PowerMeterTemplate> = object({
  id: ['id', string()],
  label: ['label', string()],
  className: ['className', peripheralClassesEnumSchema],
  deviceCategory: ['deviceCategory', deviceCategoryEnumSchema],
  channelId: ['channelId', string()],
});
