/**
 * Smart Manager APILib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { array, lazy, object, Schema, string } from '../schema';
import { Device1, device1Schema } from './device1';

/** Response from creating template */
export interface ResponseCreateTemplate {
  templateId: string;
  templateLabel: string;
  devices: Device1[];
}

export const responseCreateTemplateSchema: Schema<ResponseCreateTemplate> = object(
  {
    templateId: ['templateId', string()],
    templateLabel: ['templateLabel', string()],
    devices: ['devices', array(lazy(() => device1Schema))],
  }
);
