/**
 * Smart Manager APILib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { object, Schema, string } from '../schema';
import {
  PeripheralClassesEnum,
  peripheralClassesEnumSchema,
} from './peripheralClassesEnum';

/** Peripheral returned from scanning a DALI controller */
export interface ScannedDaliPeripheral {
  /** Refers to the class within the code that represents a device */
  className: PeripheralClassesEnum;
  /** The id of the end device e.g. aabbccdd as an enocean id for an enocean switch or 123 as a multisense network id for a smart power meter */
  hardwareId: string;
  /** The id of the multisense that this peripheral is linked to. */
  gatewayId: string;
}

export const scannedDaliPeripheralSchema: Schema<ScannedDaliPeripheral> = object(
  {
    className: ['className', peripheralClassesEnumSchema],
    hardwareId: ['hardwareId', string()],
    gatewayId: ['gatewayId', string()],
  }
);
