/**
 * Smart Manager APILib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { array, boolean, lazy, object, Schema } from '../schema';
import {
  ScannedPeripheral,
  scannedPeripheralSchema,
} from './scannedPeripheral';

export interface ScanResponse {
  /** A list of peripherals immediately available from scan. */
  scannedPeripherals: ScannedPeripheral[];
  /** Flag to say if socket events should be expected */
  hasDaliController: boolean;
}

export const scanResponseSchema: Schema<ScanResponse> = object({
  scannedPeripherals: [
    'scannedPeripherals',
    array(lazy(() => scannedPeripheralSchema)),
  ],
  hasDaliController: ['hasDaliController', boolean()],
});
