/**
 * Smart Manager APILib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { array, nullable, object, Schema, string, unknown } from '../schema';
import {
  PeripheralClassesEnum,
  peripheralClassesEnumSchema,
} from './peripheralClassesEnum';

export interface ScannedPeripheral {
  /** Refers to the class within the code that represents a device */
  className: PeripheralClassesEnum;
  /** The id of the end device e.g. aabbccdd as an enocean id for an enocean switch or 123 as a multisense network id for a smart power meter */
  hardwareId: string;
  modules: unknown[] | null;
}

export const scannedPeripheralSchema: Schema<ScannedPeripheral> = object({
  className: ['className', peripheralClassesEnumSchema],
  hardwareId: ['hardwareId', string()],
  modules: ['modules', nullable(array(unknown()))],
});
