/**
 * Smart Manager APILib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { object, Schema, string, unknown } from '../schema';

export interface Service {
  status?: unknown;
  name: string;
}

export const serviceSchema: Schema<Service> = object({
  status: ['status', unknown()],
  name: ['name', string()],
});
