/**
 * Smart Manager APILib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { number, object, Schema, string } from '../schema';

export interface SmartManagerIssue {
  id: string;
  timestamp: number;
  message: string;
  description: string;
}

export const smartManagerIssueSchema: Schema<SmartManagerIssue> = object({
  id: ['id', string()],
  timestamp: ['timestamp', number()],
  message: ['message', string()],
  description: ['description', string()],
});
