/**
 * Smart Manager APILib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { object, Schema, string } from '../schema';

export interface SmartManagerConfig {
  /** Unique ID of the device template */
  templateId: string;
}

export const smartManagerConfigSchema: Schema<SmartManagerConfig> = object({
  templateId: ['templateId', string()],
});
