/**
 * Smart Manager APILib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { array, lazy, object, optional, Schema, string } from '../schema';
import { Service, serviceSchema } from './service';

export interface SmartManagerAbout {
  appName?: string;
  release?: string;
  services: Service[];
  id: string;
  name: string;
  tenant: string;
  location: string;
  osVersion: string;
}

export const smartManagerAboutSchema: Schema<SmartManagerAbout> = object({
  appName: ['appName', optional(string())],
  release: ['release', optional(string())],
  services: ['services', array(lazy(() => serviceSchema))],
  id: ['id', string()],
  name: ['name', string()],
  tenant: ['tenant', string()],
  location: ['location', string()],
  osVersion: ['osVersion', string()],
});
