/**
 * Smart Manager APILib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { array, lazy, object, Schema, string } from '../schema';
import { Device, deviceSchema } from './device';

export interface Template {
  id: string;
  label: string;
  devices: Device[];
}

export const templateSchema: Schema<Template> = object({
  id: ['id', string()],
  label: ['label', string()],
  devices: ['devices', array(lazy(() => deviceSchema))],
});
