/**
 * Smart Manager APILib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { object, optional, Schema, string } from '../schema';

export interface UpdatePeripheral {
  label?: string;
}

export const updatePeripheralSchema: Schema<UpdatePeripheral> = object({
  label: ['label', optional(string())],
});
