/**
 * Smart Manager APILib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { array, object, optional, Schema, string } from '../schema';
import {
  ActiveConnectionStateEnum,
  activeConnectionStateEnumSchema,
} from './activeConnectionStateEnum';

export interface Wifi {
  macAddress: string;
  ipAddresses: string[];
  /** State of the connection with the wifi currently associated with () */
  state?: ActiveConnectionStateEnum;
  /** SSID of the wifi network we're currently connected to (if any) */
  ssid?: string;
}

export const wifiSchema: Schema<Wifi> = object({
  macAddress: ['macAddress', string()],
  ipAddresses: ['ipAddresses', array(string())],
  state: ['state', optional(activeConnectionStateEnumSchema)],
  ssid: ['ssid', optional(string())],
});
