/**
 * Smart Manager APILib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { Schema, stringEnum } from '../schema';

/**
 * Enum for WifiFrequencyTypeEnum
 */
export enum WifiFrequencyTypeEnum {
  Enum5 = '5',
  Enum24 = '2.4',
}

/**
 * Schema for WifiFrequencyTypeEnum
 */
export const wifiFrequencyTypeEnumSchema: Schema<WifiFrequencyTypeEnum> = stringEnum(WifiFrequencyTypeEnum);
