/**
 * Smart Manager APILib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { Schema, stringEnum } from '../schema';

/**
 * Enum for WifiFrequencyType1Enum
 */
export enum WifiFrequencyType1Enum {
  Enum5 = '5',
  Enum24 = '2.4',
}

/**
 * Schema for WifiFrequencyType1Enum
 */
export const wifiFrequencyType1EnumSchema: Schema<WifiFrequencyType1Enum> = stringEnum(WifiFrequencyType1Enum);
